jobs:
 - template: default.yml@templates
   parameters:
     codecov_token: $(CODECOV_TOKEN_SECRET)
     minrust: 1.40.0 # map_get_key_value

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.3
      endpoint: jonhoo
